baseURL = 'https://cafestationspladsen.dk'
languageCode = 'en-us'
title = 'Caf√© Stationspladsen'
paginate = 3
summaryLength = 40

[[menu.main]]
name = "Menukort"
url = "/menukort"
weight = 2


[params]
dateFormat = "2. Jan, 2006"